---
- name: Schedule a task
  hosts: proxy
  become: true
  tasks:
    - name: Ensure file exists
      file:
        path: /var/log/time.log
        state: touch
        mode: 0644
    - name: create cronjob for root
      cron:
        name: "check time"
        user: root
        hour: "*"
        job: "date >> /var/log/time.log"
